version: '2'
services:
  psql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis
  memcached:
    image: memcached
  api:
    build: .
    ports:
      - 8181:8181
  worker:
    build: .
    command: celery -A architect worker -l info
