query:
  prometheus_test_range_query:
    metric: hdd_errors
    step: 4h
    start: "2018-01-25T12:00:00Z"
    end: "2018-01-30T12:00:00Z"
  prometheus_test_instant_query:
    metric: hdd_errors
    step: 1h
    instant: "2018-01-30T12:00:00Z"
metric:
  hdd_errors:
    job: telegraf
