inventory:
  hier-cluster-inventory:
    engine: hier-cluster
    service_class_dir:
    system_class_dir:
    cluster_class_dir:
    class_dir: /srv/salt/reclass/classes
    formula_dir: /srv/salt/base
